### ISSUE TITLE
Update messaging 

### ISSUE THREAD

**Issue by Aliserag** [Aliserag/CovidImpact#14]
**Overview:**
Update messaging on homepage to reflect the open-source nature of the project.

**What needs to be done:**
Steps

1. Update messaging on homepage to reflect the open-source nature of the project and replace 'brought to you by the Fostrum team' to 'inspired by the folks at Fostrum'.

**Criteria of success:**
1. Text successfully updated

**Stakeholder:**
@aliserag

**Comment by aPruner** [comment]
I can pick this one up! :) should have a PR pretty quickly

**Comment by aPruner** [comment]
#33 was merged so this also needs to be closed @Aliserag  @NoirKomBatman
