### ISSUE TITLE
Refactor all strings for localization

### ISSUE THREAD

**Issue by Aliserag** [Aliserag/CovidImpact#21]
**Overview:**
Canada is a mosaic society with people being most comfortable in a plethora of languages. People in other countries that do not speak English may also be interested in knowing the initiatives we're taking to help businesses overcome Covid19. Translating pages into different languages would make the application more accessible.

**What needs to be done:**
1. Refactor all strings for localization

**Criteria of success:**
1. Strings refactored

**Documentation:**
https://www.npmjs.com/package/vue-intl

**Stakeholder:**
@Aliserag

**Comment by NoirKomBatman** [comment]
https://www.npmjs.com/package/vue-intl

**Comment by NoirKomBatman** [comment]
See `Hero.vue` and `i18n/messages.js` for an example on how to convert

**Comment by NoirKomBatman** [comment]
`NavBar`, `Hero`, `CallToAction` done
I dibs `Timeline`, `Runway`. @Aliserag the rest is yours.

**Comment by Aliserag** [comment]
> `NavBar`, `Hero`, `CallToAction` done
> I dibs `Timeline`, `Runway`. @Aliserag the rest is yours.

Sounds good

**Comment by NoirKomBatman** [comment]
Done. English only for now.
