### ISSUE TITLE
Remove Grey Line in News List items

### ISSUE THREAD

**Issue by Aliserag** [Aliserag/CovidImpact#6]
**Current behavior**
When visiting the news page, divs display a grey divide in the footer section for each news item.

**Expected behavior**
The entire footer should be one colour

**Steps to replicate behavior **
1. Visit the news page at https://covidimpact.ca/news and observe the footer

**Screenshots**
![image](https://user-images.githubusercontent.com/11467748/78403123-b5063c00-75b0-11ea-8379-03cfe8844ae3.png)

**Comment by aPruner** [comment]
I can take this one

**Comment by aPruner** [comment]
#34 was merged fixing this! @Aliserag @NoirKomBatman can one of you guys close it?
